const properties = [
    {
        id: 1,
        title: "property_1",
        neighborhood: "Himbi",
        city: "Goma",
        country: "DRC",
        description: "Cet appartement situé au bord du lac Kivu vous offre une vue unique sur le lac...",
        livingroom: 1,
        bedroom: 3,
        bathroom: 2,
        monthly_price: 500,
        daily_price: 50,
        availability: "available",
        image: "/assets/images/apart_1.jpg"
    },
    {
        id: 2,
        title: "property_2",
        neighborhood: "Kyeshero",
        city: "Goma",
        country: "DRC",
        description: "Cet appartement situé au bord du lac Kivu vous offre une vue unique sur le lac...",
        livingroom: 1,
        bedroom: 3,
        bathroom: 2,
        monthly_price: 300,
        daily_price: 40,
        availability: "unavailable",
        image: "/assets/images/apart_2.jpg"
    },
    {
        id: 3,
        title: "property_2",
        neighborhood: "Nguba",
        city: "Bukavu",
        country: "DRC",
        description: "Cet appartement situé au bord du lac Kivu vous offre une vue unique sur le lac...",
        livingroom: 1,
        bedroom: 5,
        bathroom: 2,
        monthly_price: 600,
        daily_price: 45,
        availability: "pending",
        image: "/assets/images/apart_3.jpg"
    },
    {
        id: 4,
        title: "property_2",
        neighborhood: "Les Volcans",
        city: "Goma",
        country: "DRC",
        description: "Cet appartement situé au bord du lac Kivu vous offre une vue unique sur le lac...",
        livingroom: 1,
        bedroom: 5,
        bathroom: 2,
        monthly_price: 350,
        daily_price: 25,
        availability: "available",
        image: "/assets/images/apart_1.jpg"
    },
    
    {
        id: 5,
        title: "property_2",
        neighborhood: "Les Volcans",
        city: "Goma",
        country: "DRC",
        description: "Cet appartement situé au bord du lac Kivu vous offre une vue unique sur le lac...",
        livingroom: 1,
        bedroom: 5,
        bathroom: 2,
        monthly_price: 350,
        daily_price: 25,
        availability: "available",
        image: "/assets/images/apart_1.jpg"
    },
    
    {
        id: 6,
        title: "property_2",
        neighborhood: "Les Volcans",
        city: "Goma",
        country: "DRC",
        description: "Cet appartement situé au bord du lac Kivu vous offre une vue unique sur le lac...",
        livingroom: 1,
        bedroom: 5,
        bathroom: 2,
        monthly_price: 350,
        daily_price: 25,
        availability: "available",
        image: "/assets/images/apart_1.jpg"
    },
    {
        id: 7,
        title: "property_3",
        neighborhood: "Les Volcans",
        city: "Goma",
        country: "DRC",
        description: "Cet appartement situé au bord du lac Kivu vous offre une vue unique sur le lac...",
        livingroom: 1,
        bedroom: 5,
        bathroom: 2,
        monthly_price: 350,
        daily_price: 25,
        availability: "available",
        image: "/assets/images/apart_1.jpg"
    },
    {
        id: 8,
        title: "property_1",
        neighborhood: "Les Volcans",
        city: "Goma",
        country: "DRC",
        description: "Cet appartement situé au bord du lac Kivu vous offre une vue unique sur le lac...",
        livingroom: 1,
        bedroom: 5,
        bathroom: 2,
        monthly_price: 350,
        daily_price: 25,
        availability: "available",
        image: "/assets/images/apart_1.jpg"
    },
    {
        id: 9,
        title: "property_1",
        neighborhood: "Les Volcans",
        city: "Goma",
        country: "DRC",
        description: "Cet appartement situé au bord du lac Kivu vous offre une vue unique sur le lac...",
        livingroom: 1,
        bedroom: 5,
        bathroom: 2,
        monthly_price: 350,
        daily_price: 25,
        availability: "unavailable",
        image: "/assets/images/apart_2.jpg"
    },
    {
        id: 10,
        title: "property_1",
        neighborhood: "Les Volcans",
        city: "Goma",
        country: "DRC",
        description: "Cet appartement situé au bord du lac Kivu vous offre une vue unique sur le lac...",
        livingroom: 1,
        bedroom: 5,
        bathroom: 2,
        monthly_price: 350,
        daily_price: 25,
        availability: "available",
        image: "/assets/images/apart_3.jpg"
    },
    {
        id: 11,
        title: "property_1",
        neighborhood: "Les Volcans",
        city: "Goma",
        country: "DRC",
        description: "Cet appartement situé au bord du lac Kivu vous offre une vue unique sur le lac...",
        livingroom: 1,
        bedroom: 5,
        bathroom: 2,
        monthly_price: 350,
        daily_price: 25,
        availability: "Pending",
        image: "/assets/images/apart_2.jpg"
    },
    {
        id: 12,
        title: "property_1",
        neighborhood: "Les Volcans",
        city: "Goma",
        country: "DRC",
        description: "Cet appartement situé au bord du lac Kivu vous offre une vue unique sur le lac...",
        livingroom: 1,
        bedroom: 5,
        bathroom: 2,
        monthly_price: 350,
        daily_price: 25,
        availability: "unavailable",
        image: "/assets/images/apart_2.jpg"
    },
]

export default properties;